import { REVIEWS } from "./reviews";
import type { Place } from "../types/stays";
export const PLACES: Place[] = [
  {
    id: 354121,
    title: "Grand Hotel Vesuvio",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 150,
    subtotal: 181,
    imgSrc:
      "https://images.unsplash.com/photo-1715343413411-116c0ec80c08?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    listing_status: "listed",
    coords: [27.717245, 85.323959],
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 5123123,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
          { count: 1, type: "twin" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 321313,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 39278137,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
    review: REVIEWS,
  },
  {
    id: 512312,
    title: "Candel light sparrow",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 200,
    subtotal: 181,
    coords: [27.742245, 85.343959],
    imgSrc:
      "https://images.unsplash.com/photo-1651185792161-7d81c0c2f60b?q=80&w=1924&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    listing_status: "unlisted",
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 5123123,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
          { count: 3, type: "twin" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 52123132,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 8547432,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
    review: REVIEWS,
  },
  {
    id: 8252543,
    title: "Lorem ipsum monosu mesudno",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 84,
    subtotal: 181,
    coords: [27.797245, 85.253959],
    imgSrc:
      "https://images.unsplash.com/photo-1694543649187-4fdc5d1f7384?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 92524234,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 825423424,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 72423452,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
  },
  {
    id: 3541921,
    title: "Grand Hotel Vesuvio",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 150,
    subtotal: 181,
    imgSrc:
      "https://images.unsplash.com/photo-1715343413411-116c0ec80c08?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    listing_status: "listed",
    coords: [27.717245, 85.323959],
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 5123123,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
          { count: 1, type: "twin" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 321313,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 39278137,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
    review: REVIEWS,
  },
  {
    id: 5512312,
    title: "Candel light sparrow",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 200,
    subtotal: 181,
    coords: [27.742245, 85.343959],
    imgSrc:
      "https://images.unsplash.com/photo-1651185792161-7d81c0c2f60b?q=80&w=1924&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    listing_status: "unlisted",
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 5123123,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
          { count: 3, type: "twin" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 52123132,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 8547432,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
    review: REVIEWS,
  },
  {
    id: 82525423,
    title: "Lorem ipsum monosu mesudno",
    description:
      "Incredible Sea Views, 3 different Pools, Newly renovated rooms.",
    rating: 4.9,
    ratingTotal: 120,
    total: 84,
    subtotal: 181,
    coords: [27.797245, 85.253959],
    imgSrc:
      "https://images.unsplash.com/photo-1694543649187-4fdc5d1f7384?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    address: {
      state: "Florida",
      city: "Longwood",
      street: "1020 Waverly Dr.",
      zip: "32750",
    },
    rooms: [
      {
        id: 92524234,
        name: "3B King superior Room",
        beds: [
          { count: 2, type: "king" },
          { count: 1, type: "queen" },
        ],
        price: 282,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 825423424,
        name: "One bedroom Suite",
        beds: [{ count: 1, type: "king" }],
        price: 132,
        quantity: 3,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
      {
        id: 72423452,
        name: "2b Jr Suite",
        beds: [{ count: 2, type: "king" }],
        price: 150,
        quantity: 1,
        images: "/images/global/galleria_umberto.png",
        roomType: "suite",
        stock: 4,
      },
    ],
  },
];
